### ISSUE TITLE
建议增加以下两点

### ISSUE THREAD

**Issue by geraldlrh** [jieyou/remote_inspect_web_on_real_device#2]
1. http://www.debuggap.com/
2. http://www.html-js.com/article/3076

**Comment by jieyou** [comment]
感谢关注这个项目。上述2是一个非常好的能调试微信webview的办法。
不知你是否方便fork本项目，然后把上述2加进去，提交一个pr？

**Comment by jieyou** [comment]
已经merge了你的 https://github.com/jieyou/remote_inspect_web_on_real_device/pull/3
