### ISSUE TITLE
调试Android上的x5内核

### ISSUE THREAD

**Issue by zzuieliyaoli** [jieyou/remote_inspect_web_on_real_device#4]
微信出官方调试工具了。

支持本地调试微信公众号，远程调试微信网页
http://blog.qqbrowser.cc/

**Comment by jieyou** [comment]
@zzuieliyaoli   如果方便，请直接fork后加到文中，然后提交pull request，谢谢

**Comment by wangpin34** [comment]
@zzuieliyaoli 貌似现在只有mac上使用的测试版本。

**Comment by jieyou** [comment]
现在已经有人补充了，没有看清是不是你：）
